#!/bin/bash

FILES=()

export DEBIAN_FRONTEND=noninteractive

IFSBAK=$IFS
IFS=''

all_includes=()

for file in /etc/nginx/sites-enabled/*; do
  readarray -t lines < $file
  if [ 0 != ${#lines[@]} ]; then
    content_no_comment=()
    for line in "${lines[@]}"; do
      is_commented=`echo $line | sed 's/^\s*//' | sed 's/^#.*//'`
      if [ ! -z "$is_commented" ]; then
        content_no_comment+=($line)
      fi
    done
    site=`printf "%s\n" "${content_no_comment[@]}" | grep server_name | sed 's/^\s*//' | sed 's/server_name\s*//' | sed 's/;//' | cut -d ' ' -f 1`
    if [ '_' != ${site:0:1} ]; then
      content=`printf "%s\n" "${lines[@]}"`
      includes=`echo $content | grep include`
      content=`printf "+%s\n" "${lines[@]}"`
      readarray -t includes <<< "$includes"
      if [ 0 != ${#includes[@]} ]; then
        for include in "${includes[@]}"; do
          include=`echo $include | sed 's/^\s*include\s*//' | sed 's/^#.*//' | sed 's/;$//'`
          if [ ! -z "$include" ]; then
            if [ '/' != ${include:0:1} ]; then
              include="/etc/nginx/$include"
            fi
            if [[ $include == *'*'* ]]; then
              include_list=`ls $include`
              readarray -t include_list <<< "$include_list"
              for include_item in "${include_list[@]}"; do
                all_includes+=($include_item)
              done
            else
              all_includes+=($include)
            fi
          fi
        done
      fi
      FILES+=($site)
      FILES+=($content)
    fi
  fi
done

if [ 0 != ${#all_includes[@]} ]; then
  all_includes=($(printf "%s\n" "${all_includes[@]}" | sort -u))
  readarray -t all_includes <<< "$all_includes"
  for file in "${all_includes[@]}"; do
    readarray -t lines < $file
    content=`printf "+%s\n" "${lines[@]}"`
    FILES+=($file)
    FILES+=($content)
  done
fi

printf "%s\n" "${FILES[@]}"

IFS=$IFSBAK
