#!/bin/bash

FILES=

export DEBIAN_FRONTEND=noninteractive

sites=`ls /etc/nginx/sites-enabled`
readarray -t sites <<< "$sites"

all_includes=()

IFSBAK=$IFS
IFS=" "

for site in "${sites[@]}"; do
  content=`cat /etc/nginx/sites-enabled/$site`
  if [ ! -z "$content" ]; then
    site=`grep server_name <<< $content`
    site=`sed 's/^\s//' <<< $site`
    site=`echo $site | sed 's/server_name\s*//' | sed 's/;//' | cut -d ' ' -f 1`

    if [ ! -z "$site" ] && [ '_' != ${site:0:1} ] && [ '#' != ${site:0:1} ]; then
      includes=`grep include <<< $content`
      readarray -t includes <<< "$includes"
      for include in "${includes[@]}"; do
        include=`echo $include | sed 's/^\s*include\s*//' | sed 's/^#.*//' | sed 's/;$//'`
        if [ ! -z "$include" ]; then
          if [ '/' != ${include:0:1} ]; then
            include="/etc/nginx/$include"
          fi
          if [[ $include == *'*'* ]]; then
            include_list=`ls $include`
            readarray -t include_list <<< "$include_list"
            for include_item in "${include_list[@]}"; do
              all_includes+=($include_item)
            done
          else
            all_includes+=($include)
          fi
        fi
      done
      content=`sed 's/^/+/' <<< $content`
      FILES+="$site\n$content"
    fi
  fi
done

all_includes=($(printf "%s\n" "${all_includes[@]}" | sort -u))
readarray -t all_includes <<< "$all_includes"
for include in "${all_includes[@]}"; do
  content=`cat $include`
  content=`sed 's/^/+/' <<< $content`
  include=`sed 's|/etc/nginx/||' <<< $include`
  FILES+="\n$include\n$content"
done

echo -e $FILES

IFS=$IFSBAK
