#!/bin/bash

OS_NAME=
OS_VERSION=
OS_CODE_NAME=
OS_DESCRIPTION=
ARCH=
export DEBIAN_FRONTEND=noninteractive

[ -e '/bin/uname' ] && uname='/bin/uname' || uname='/usr/bin/uname'
ARCH=`uname -m`
OPERATING_SYSTEM=`uname -s`
if [ "$OPERATING_SYSTEM" = 'Linux' ]; then
  if [ -e '/etc/debian_version' ]; then
    if [ -e '/etc/lsb-release' ]; then
      . /etc/lsb-release
      OS_NAME=$DISTRIB_ID
      OS_CODE_NAME=$DISTRIB_CODENAME
      OS_VERSION=$DISTRIB_RELEASE
      OS_DESCRIPTION=$DISTRIB_DESCRIPTION
    fi
  fi
fi

echo "architecture=$ARCH&os-name=$OS_NAME&os-version=$OS_VERSION&os-description=$OS_DESCRIPTION"
