#!/bin/bash

# Memory in MB.
MEM=`echo $(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / (1024 * 1024)))`

# Round to GB.
MEM=`echo $((($MEM / 1000) + ($MEM % 1000 > 0)))`

# vCPU.
VCPU=`cat /proc/cpuinfo | grep processor | wc -l`

echo "mem=$MEM&vcpu=$VCPU"
